[features]
seeds = false
skip-lint = false
init-if-needed = true

[programs.localnet]
escrow_program = "25ecY9sGUkFyy78aYaSbdWGMgySSKZvPjQunf6Uk23qk"

[programs.devnet]
escrow_program = "25ecY9sGUkFyy78aYaSbdWGMgySSKZvPjQunf6Uk23qk"

[programs.mainnet]
escrow_program = "25ecY9sGUkFyy78aYaSbdWGMgySSKZvPjQunf6Uk23qk"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 'tests/**/*.js'"

[toolchain]
anchor_version = "0.31.0"
