[features]
seeds = false
skip-lint = false

[programs.localnet]
escrow_program = "你的程序ID"

[programs.devnet]
escrow_program = "你的程序ID"

[programs.mainnet]
escrow_program = "你的程序ID"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
