[features]
seeds = false
skip-lint = false
init-if-needed = true

[programs.localnet]
escrow_program = "E8vcELiVSEk8BLyHGY697muumtfqm8t8vEP4Mt5thYg7"

[programs.devnet]
escrow_program = "E8vcELiVSEk8BLyHGY697muumtfqm8t8vEP4Mt5thYg7"

[programs.mainnet]
escrow_program = "E8vcELiVSEk8BLyHGY697muumtfqm8t8vEP4Mt5thYg7"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 'tests/**/*.js'"

[toolchain]
anchor_version = "0.31.0"
