[package]
name = "escrow-program"
version = "0.1.0"
edition = "2021"
description = "时间锁定多签名托管程序"
authors = ["Mobazha"]

[lib]
crate-type = ["cdylib", "lib"]
name = "escrow_program"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.31.0"
anchor-spl = "0.31.0"

# 使用原项目的solana版本
solana-program = "2.2.0"

# 添加原项目所需的其他依赖
borsh = "0.10.3"
borsh-derive = "0.10.3"
thiserror = "2.0"
arrayref = "0.3.9"
spl-token = "7.0.0"

# 可选依赖(Anchor可能已经包含了这些功能)
solana-program-pack = "2.2.0" 
solana-pubkey = { version = "2.2.0", features = ["bytemuck"] } 